#!/usr/bin/env python3
"""Normalize ClangSharp imports and CLR-specific alignment without changing ABI fields."""
from pathlib import Path
import re
import sys
s=Path(sys.argv[1]).read_text()
s=re.sub(r'\[(?:return: )?NativeTypeName\("(?:[^"\\]|\\.)*"\)\]\s*','',s)
s=s.replace('[DllImport("LiteHtmlLib", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]','[LibraryImport("LiteHtmlLib")]\n    [UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]')
s=s.replace('public static extern ','public static partial ')
a=s.index('public partial struct lh_color');b=s.index('public partial struct lh_rect')
s=s[:a]+'''[StructLayout(LayoutKind.Explicit, Size = 4)]
public partial struct lh_color
{
    [FieldOffset(0)] private uint alignment;
    [FieldOffset(0)] public byte r;
    [FieldOffset(1)] public byte g;
    [FieldOffset(2)] public byte b;
    [FieldOffset(3)] public byte a;
}

'''+s[b:]
a=s.index('public unsafe partial struct lh_font_desc');b=s.index('public partial struct lh_font_metrics')
s=s[:a]+s[a:b].replace('    public uint padding;','    // Native 64-bit trailing padding is supplied by CLR pointer alignment.')+s[b:]
header=Path(__file__).with_name("include").joinpath("lh_api.h").read_text()
exports=set(re.findall(r"LH_API\s+[^;]*?\b(lh_\w+)\s*\(",header))
imports=set(re.findall(r"\[LibraryImport\([^]]+\)\]\s*\[UnmanagedCallConv\([^]]+\]\)\]\s*public static partial [^;]*?\b(lh_\w+)\s*\(",s))
if exports != imports:
    raise SystemExit(f"Generated export mismatch: missing={exports-imports}, extra={imports-exports}")
if "DllImport(" in s:
    raise SystemExit("Unnormalized DllImport in generated bindings")
Path(sys.argv[2]).write_text('// Generated by ClangSharp 21.1.8.4 and normalize-bindings.py.\n'+s)
